version: "3.8"

services:
  web:
    build: .
    command: ./start-dev.sh
    ports:
      - "8000:8000"
    environment:
      - DEBUG=true
    depends_on:
      - celery
      - redis
    networks:
      - shared-net
    volumes:
      - .:/app  

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollamavolume:/root/.ollama
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0
    restart: unless-stopped
    networks:
      - shared-net

  redis:
    image: redis:alpine
    restart: always
    networks:
      - shared-net

  celery:
    build:
      context: .
      dockerfile: celery.dockerfile
    command: celery -A app.services.celery_worker.c_worker worker --loglevel=info --pool=solo
    restart: always
    depends_on:
      - redis
    networks:
      - shared-net

  flower:
    image: mher/flower:1.2
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    restart: always
    ports:
      - "5555:5555"
    depends_on:
      - celery
    networks:
      - shared-net
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data
    volumes:
      - minio_data:/data
    networks:
      - shared-net

  loki:
    image: grafana/loki:2.9.0
    container_name: loki
    ports:
      - "3100:3100"
    command: ["-config.file=/etc/loki/local-config.yaml"]
    volumes:
      - loki-data:/loki
    networks:
      - shared-net
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    depends_on:
      - loki
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
      - ./logging/grafana/provisioning:/etc/grafana/provisioning:ro
    restart: unless-stopped
    networks:
      - shared-net

  promtail:
    image: grafana/promtail:2.9.0
    container_name: promtail
    volumes:
      - /var/log:/var/log:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ./logging/promtail-config.yml:/etc/promtail/config.yml:ro
    command: ["-config.file=/etc/promtail/config.yml"]
    networks:
      - shared-net
    restart: unless-stopped
    depends_on:
      - loki

volumes:
  ollamavolume:
  minio_data:
  loki-data:
  grafana-data:
  
networks:
  shared-net:
    driver: bridge
