version: "3.8"

services:
  web:
    build: .
    command: ./start-dev.sh
    ports:
      - "8000:8000"
    environment:
      - DEBUG=true
    depends_on:
      - celery
      - redis
    networks:
      - shared_net
    volumes:
      - .:/app  # <-- bind mount local directory

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollamavolume:/root/.ollama
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0
    restart: unless-stopped
    networks:
      - shared_net

  redis:
    image: redis:alpine
    restart: always
    networks:
      - shared_net

  celery:
    build:
      context: .
      dockerfile: celery.dockerfile
    command: celery -A app.services.celery_worker.c_worker worker  --loglevel=info --pool=solo
    restart: always
    depends_on:
      - redis
    networks:
      - shared_net

  flower:
    image: mher/flower:1.2
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    restart: always
    ports:
      - "5555:5555"
    depends_on:
      - celery
    networks:
      - shared_net
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data
    volumes:
      - minio_data:/data
    networks:
      - shared_net



volumes:
  ollamavolume:
  minio_data:
networks:
  shared_net:
    driver: bridge
