apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.dev.yml convert
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: celery
  name: celery
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: celery
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f docker-compose.dev.yml convert
        kompose.version: 1.37.0 (fb0539e64)
      labels:
        io.kompose.service: celery
    spec:
      containers:
        - name: celery
          image: celery:0.1.0
          imagePullPolicy: IfNotPresent
          args:
            - celery
            - -A
            - app.services.celery_worker.c_worker
            - worker
            - --loglevel=info
            - --pool=solo
      restartPolicy: Always
