apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.dev.yml convert
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: flower
  name: flower
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: flower
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f docker-compose.dev.yml convert
        kompose.version: 1.37.0 (fb0539e64)
      labels:
        io.kompose.service: flower
    spec:
      containers:
        - env:
            - name: CELERY_BROKER_URL
              value: redis://redis:6379/0
          image: mher/flower:1.2
          name: flower
          ports:
            - containerPort: 5555
      restartPolicy: Always
