"""add audio_key and report_key columns to jobs table

Revision ID: 6a9f63cbea8c
Revises: 6f6b05fb8d8f
Create Date: 2025-09-09 15:02:51.868519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a9f63cbea8c'
down_revision: Union[str, None] = '6f6b05fb8d8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('audio_key', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('report_key', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'report_key')
    op.drop_column('jobs', 'audio_key')
    # ### end Alembic commands ###
